version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nox_user
      POSTGRES_PASSWORD: nox_pass
      POSTGRES_DB: nox_test
    ports:
      - "5432:5432"
    volumes:
      - nox_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: nox-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  nox_pgdata:
